export const GET_POKEMONS = 'GET_POKEMONS';
export const GET_POKEMONS_SUCCESS = 'GET_POKEMONS_SUCCESS';
export const GET_POKEMONS_FAIL = 'GET_POKEMONS_FAIL';

export const GET_CATCHED_POKEMONS = 'GET_CATCHED_POKEMONS';
export const GET_CATCHED_POKEMONS_SUCCESS = 'GET_CATCHED_POKEMONS_SUCCESS';
export const GET_CATCHED_POKEMONS_FAIL = 'GET_CATCHED_POKEMONS_FAIL';

export const ON_CATCH_POKEMON = 'ON_CATCH_POKEMON';
export const ON_CATCH_POKEMON_SUCCESS = 'ON_CATCH_POKEMON_SUCCESS';
export const ON_CATCH_POKEMON_FAIL = 'ON_CATCH_POKEMON_FAIL';

export const GET_THE_POKEMON = 'GET_THE_POKEMON';
export const GET_THE_POKEMON_SUCCESS = 'GET_THE_POKEMON_SUCCESS';
export const GET_THE_POKEMON_FAIL = 'GET_THE_POKEMON_FAIL';

export const CHANGE_POKEMON_STATUS = 'CHANGE_POKEMON_STATUS';

export const IS_GOT_POKEMONS_ALL = 'IS_GOT_POKEMONS_ALL';
export const IS_GOT_POKEMONS_CATCHED = 'IS_GOT_POKEMONS_CATCHED';


